### ISSUE TITLE
Forcing V3 mount on RHEL7

### ISSUE THREAD

**Issue by paulz-gh** [derdanne/puppet-nfs#131]
Hi it looks like forcing a mount to V3 using nfs::client:: mount attributes in hiera.
For all versions except RHEL the nfs_options param contains nfsvers=3.
Why is this missing for RHEL ?
Is there another way on RHEL to force v3 mount ?

**Comment by oberon227** [comment]
>  Why is this missing for RHEL ?
I can't speak directly to this, but I'd guess it's because RHEL has good support for v4, so the author didn't see a reason to include it.  (Also, if I'm not mistaken, in the case of a v4-capable client, and a v3-only server, the client will start with v4, but downgrade to v3 once it finds out the server is v3.)

>  Is there another way on RHEL to force v3 mount ?
Absolutely!  You can use the nfs::client_nfs_options parameter to override the default option.  You could copy what's in params.pp and add the `nfsvers=3` option, or you could use a custom line entirely your own.
